begin;
select plan(21);
select has_table('public','media_attachments','media exists');
select has_table('public','media_references','references exist');
select has_table('public','custom_stickers','sticker library exists');
select has_table('public','push_jobs','durable push jobs exist');
select has_table('public','scheduled_messages','encrypted schedules exist');
select has_function('public','chat_unread',array['uuid'],'unread RPC exists');
select ok(not has_table_privilege('anon','public.media_attachments','select'),'anonymous cannot list media');
select ok(not has_table_privilege('authenticated','public.media_attachments','insert'),'client cannot fabricate storage paths');
select ok(not has_table_privilege('authenticated','public.media_attachments','update'),'client cannot mark uploads complete');
select ok(not has_function_privilege('authenticated','public.claim_media_deletion(uuid,uuid)','execute'),'deletion claims are server-only');
select ok(not has_function_privilege('authenticated','public.stale_media_candidates()','execute'),'orphan cleanup is server-only');
select ok(not has_function_privilege('authenticated','public.claim_push_jobs(uuid)','execute'),'push worker is server-only');
select ok(not has_function_privilege('authenticated','public.count_unread_for_user(uuid,uuid)','execute'),'cannot query another user counter');
select ok(not has_table_privilege('authenticated','public.push_jobs','select'),'private delivery queue is server-only');
select ok(not has_table_privilege('authenticated','public.scheduled_messages','update'),'client cannot publish its own scheduled row');
select has_trigger('public','messages','messages_media','references bind transactionally');
select has_trigger('public','message_receipts','receipts_relation','receipt relation is checked');
select has_trigger('public','message_reactions','reactions_relation','reaction relation is checked');
select is((select count(*)::integer from pg_class where relnamespace='public'::regnamespace and relname in ('media_attachments','media_references','custom_stickers','push_jobs','push_job_deliveries','scheduled_messages','starred_messages','pinned_messages','user_notification_settings') and relrowsecurity),9,'RLS enabled on every new table');
select ok(not exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname in ('claim_media_deletion','stale_media_candidates','count_unread_for_user','claim_push_jobs','publish_scheduled_messages','consume_rate_limit','join_quick_access') and (has_function_privilege('anon',oid,'execute') or has_function_privilege('authenticated',oid,'execute'))),'all privileged RPCs reject browser roles, including default grants');
select ok(not exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname in ('claim_media_deletion','stale_media_candidates','count_unread_for_user','claim_push_jobs','publish_scheduled_messages','consume_rate_limit','join_quick_access') and not has_function_privilege('service_role',oid,'execute')),'service role retains every privileged RPC');
select * from finish();
rollback;
